---
title: "unzip"
output: html_document
---

```{r}
library(R.matlab)
library(jsonlite)
library(purrr)
library(data.table)
library(ggplot2)
library(dplyr)
```


```{r}
dat <- readMat('./DATA_BLSA.mat')

```

```{r}
mes <- dat$measures
#mes2 <- as.data.frame(mes)
```

```{r}
for (i in 1:49) {
  assign( paste("bundle_", i, sep = ""), as.data.frame(mes[,i,]) )
}
```

```{r}
colnames(bundle_1) <- paste("b1", colnames(bundle_1), sep = "_")
colnames(bundle_2) <- paste("b2", colnames(bundle_2), sep = "_")
colnames(bundle_3) <- paste("b3", colnames(bundle_3), sep = "_")
colnames(bundle_4) <- paste("b4", colnames(bundle_4), sep = "_")
colnames(bundle_5) <- paste("b5", colnames(bundle_5), sep = "_")
colnames(bundle_6) <- paste("b6", colnames(bundle_6), sep = "_")
colnames(bundle_7) <- paste("b7", colnames(bundle_7), sep = "_")
colnames(bundle_8) <- paste("b8", colnames(bundle_8), sep = "_")
colnames(bundle_9) <- paste("b9", colnames(bundle_9), sep = "_")

colnames(bundle_10) <- paste("b10", colnames(bundle_10), sep = "_")
colnames(bundle_11) <- paste("b11", colnames(bundle_11), sep = "_")
colnames(bundle_12) <- paste("b12", colnames(bundle_12), sep = "_")
colnames(bundle_13) <- paste("b13", colnames(bundle_13), sep = "_")
colnames(bundle_14) <- paste("b14", colnames(bundle_14), sep = "_")
colnames(bundle_15) <- paste("b15", colnames(bundle_15), sep = "_")
colnames(bundle_16) <- paste("b16", colnames(bundle_16), sep = "_")
colnames(bundle_17) <- paste("b17", colnames(bundle_17), sep = "_")
colnames(bundle_18) <- paste("b18", colnames(bundle_18), sep = "_")
colnames(bundle_19) <- paste("b19", colnames(bundle_19), sep = "_")

colnames(bundle_20) <- paste("b20", colnames(bundle_20), sep = "_")
colnames(bundle_21) <- paste("b21", colnames(bundle_21), sep = "_")
colnames(bundle_22) <- paste("b22", colnames(bundle_22), sep = "_")
colnames(bundle_23) <- paste("b23", colnames(bundle_23), sep = "_")
colnames(bundle_24) <- paste("b24", colnames(bundle_24), sep = "_")
colnames(bundle_25) <- paste("b25", colnames(bundle_25), sep = "_")
colnames(bundle_26) <- paste("b26", colnames(bundle_26), sep = "_")
colnames(bundle_27) <- paste("b27", colnames(bundle_27), sep = "_")
colnames(bundle_28) <- paste("b28", colnames(bundle_28), sep = "_")
colnames(bundle_29) <- paste("b29", colnames(bundle_29), sep = "_")

colnames(bundle_30) <- paste("b30", colnames(bundle_30), sep = "_")
colnames(bundle_31) <- paste("b31", colnames(bundle_31), sep = "_")
colnames(bundle_32) <- paste("b32", colnames(bundle_32), sep = "_")
colnames(bundle_33) <- paste("b33", colnames(bundle_33), sep = "_")
colnames(bundle_34) <- paste("b34", colnames(bundle_34), sep = "_")
colnames(bundle_35) <- paste("b35", colnames(bundle_35), sep = "_")
colnames(bundle_36) <- paste("b36", colnames(bundle_36), sep = "_")
colnames(bundle_37) <- paste("b37", colnames(bundle_37), sep = "_")
colnames(bundle_38) <- paste("b38", colnames(bundle_38), sep = "_")
colnames(bundle_39) <- paste("b39", colnames(bundle_39), sep = "_")

colnames(bundle_40) <- paste("b40", colnames(bundle_40), sep = "_")
colnames(bundle_41) <- paste("b41", colnames(bundle_41), sep = "_")
colnames(bundle_42) <- paste("b42", colnames(bundle_42), sep = "_")
colnames(bundle_43) <- paste("b43", colnames(bundle_43), sep = "_")
colnames(bundle_44) <- paste("b44", colnames(bundle_44), sep = "_")
colnames(bundle_45) <- paste("b45", colnames(bundle_45), sep = "_")
colnames(bundle_46) <- paste("b46", colnames(bundle_46), sep = "_")
colnames(bundle_47) <- paste("b47", colnames(bundle_47), sep = "_")
colnames(bundle_48) <- paste("b48", colnames(bundle_48), sep = "_")
colnames(bundle_49) <- paste("b49", colnames(bundle_49), sep = "_")

```

```{r}
measures <- cbind(bundle_1,bundle_2,bundle_3,bundle_4,bundle_5,
                  bundle_6,bundle_7,bundle_8,bundle_9,bundle_10,
                  bundle_11,bundle_12,bundle_13,bundle_14,bundle_15,
                  bundle_16,bundle_17,bundle_18,bundle_19,bundle_20,
                  bundle_21,bundle_22,bundle_23,bundle_24,bundle_25,
                  bundle_26,bundle_27,bundle_28,bundle_29,bundle_30,
                  bundle_31,bundle_32,bundle_33,bundle_34,bundle_35,
                  bundle_36,bundle_37,bundle_38,bundle_39,bundle_40,
                  bundle_41,bundle_42,bundle_43,bundle_44,bundle_45,
                  bundle_46,bundle_47,bundle_48,bundle_49)
```

```{r}
DWIcorr <- t(as.data.frame(dat$DWIcorr))
colnames(DWIcorr) <- "DWIcorr"

age <- t(as.data.frame(dat$age))
colnames(age) <- "age"

base <- t(as.data.frame(dat$base))
colnames(base) <- "base"

dataset <- t(as.data.frame(dat$dataset))
colnames(dataset) <- "dataset"

dx <- t(as.data.frame(dat$dx))
colnames(dx) <- "dx"

hand <- t(as.data.frame(dat$hand))
colnames(hand) <- "hand"

scanner <- t(as.data.frame(dat$scanner))
colnames(scanner) <- "scanner"

session <- t(as.data.frame(dat$session))
colnames(session) <- "session"

sex <- t(as.data.frame(dat$sex))
colnames(sex) <- "sex"

subject <- t(as.data.frame(dat$subject))
colnames(subject) <- "subject"

tsb <- t(as.data.frame(dat$tsb))
colnames(tsb) <- "tsb"
```

```{r}
final <- cbind(DWIcorr, age, base, dataset, subject, dx, hand, scanner,
               session, sex, tsb, measures)
final[is_empty(final)] = NA
#final<-subset(final,dx!=2)
#final<-subset(final,dx!=3)
#final<-subset(final,dx!=4)

final %>% head()
helper <- final[!duplicated(final[c("subject", "dx")]),] %>% select("subject", "dx", everything()) 
hist(final$dx)
duplicated(final[c("subject", "dx")])
helper[duplicated(helper[c("subject")]),]
```

```{r}
write.csv(final, file = "reformated_data.csv")

```


